### ISSUE TITLE
Refresh ci-debian-buster container image used for build

### ISSUE THREAD

**Issue by planetf1** [open-quantum-safe/ci-containers#74]
Followon from open-quantum-safe/liboqs#1702

The openquantumsafe/ci-debian-custer-amd64:latest image is used as part of our ci process

When working on the above PR I noticed we weren't pinning the version spec of this image (though the tooling did not detect this).

I inspected the image with a [scan on quay.io](https://quay.io/repository/planetf1/ci-debian-buster-amd64/manifest/sha256:b44ec894a0071432ca993aac617e2e503d03984f2079eee48a98a136fe0f0dbc?tab=vulnerabilities)

This is used for testing/verification, rather than supplying images for consumers, but it looks as if it could do with being updated - any images/sw used for tests could be compromised to hide an injected vulnerability.

The current image has quite old java (1.11.0), and also older versions of qemu and other tools. [See list](https://quay.io/repository/planetf1/ci-debian-buster-amd64/manifest/sha256:b44ec894a0071432ca993aac617e2e503d03984f2079eee48a98a136fe0f0dbc?tab=packages)

**Comment by dstebila** [comment]
Okay, I've moved this to the ci-containers repository and assigned to @planetf1

**Comment by ryjones** [comment]
> Please go ahead, Douglas. I don't need more permissions -- very much to the contrary.

This is confusing. You have `write` access to both repos, so you should [have permission to transfer the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository). 
<img width="186" alt="Screenshot 2024-04-24 at 04 52 30" src="https://github.com/open-quantum-safe/ci-containers/assets/466142/93dae2d8-7def-404a-b7b5-0188a957d608">

[As far as assigning issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users), @planetf1 isn't a member of the org with any permissions, and may need added.

**Comment by baentsch** [comment]
> This is confusing. You have write access to both repos

Thanks for taking a look. I tried again and realized a UI "feature" I wasn't aware of: As there are too many repos I can transfer to, only some are displayed in the "transfer pop-up". If I manually type in a non-displayed target repo to the search box, it becomes visible and the transfer would/should succeed. Sorry for making you look into this.

**Comment by baentsch** [comment]
This is to question whether it's really sensible to put work into Buster: It's running [out of support this June](https://www.debian.org/releases/). Suggest to rather put effort into moving to Bookworm (if at all -- Debian is none of the [OQS supported platforms](https://github.com/open-quantum-safe/liboqs/blob/main/PLATFORMS.md))...

**Comment by planetf1** [comment]
@baentsch agree with bookworm, but thanks for the pointer. It doesn't even appear in Tier 3 of your list. We do refer to debian in various places in our build etc so it may be preferable to retain
